### ISSUE TITLE
Replace OpenTelemetry Jaeger exporter with the default OTLP exporter

### ISSUE THREAD

**Issue by ppatierno** [strimzi/client-examples#102]
Strimzi components already moved to use the OTLP exporter (instead of the Jaeger one) for the OpenTelemetry support.
I think that the examples should do the same, as it is the default.
In order to do that, examples should not have the `opentelemetry-exporter-jaeger` dependency but the `opentelemetry-exporter-otlp`.
We can even get rid of the `OTEL_TRACES_EXPORTER` env var in the YAMLs because OTLP is the default protocol for OpenTelemetry. We should also replace `OTEL_EXPORTER_JAEGER_ENDPOINT` with `OTEL_EXPORTER_OTLP_ENDPOINT` env var (it uses port 4317).
Finally, this should be anyway tested with a Jaeger backend exposing an OTLP endpoint. This can be enabled starting up Jaeger with `COLLECTOR_OTLP_ENABLED=true` env var.

**Comment by ppatierno** [comment]
@OwenCorrigan76 do you think it's something you can work on?

**Comment by OwenCorrigan76** [comment]
@ppatierno Yes, I'll give it my best shot.
