### ISSUE TITLE
Move the Vert.x HTTP clients examples to a newer Vert.x version 

### ISSUE THREAD

**Issue by ppatierno** [strimzi/client-examples#108]
The Vert.x HTTP clients examples are using a really old Vert.x version 3.7.1.
We should move to a newer one (i.e. 4.3.7) but it would mean a refactoring because some bigger changes in Vert.x (i.e. `Promise` instead of `Future` and more).
Anyway, it should be done to avoid temporary fixes like the one I made via #106 to override Jackson Databind with an older version just because of the old Vert.x one.

**Comment by OwenCorrigan76** [comment]
Resolved with the PR: https://github.com/strimzi/client-examples/pull/124
