### ISSUE TITLE
ThreadPoolExecutor for producing data

### ISSUE THREAD

**Issue by FridMehdi** [strimzi/client-examples#11]
Hello Strimzi Team it's possible to run a pool of thread to produce data to my cluster with this example i went to attempt 800000 TPS per second. knowing that we should waiting some deley  `Thread.sleep(config.getDelay());`

**Comment by scholzj** [comment]
This example was not really written for performance testing but rather to just make sure the cluster works and to give an example. I think tat if you want to use it to produce 800k TPS you will need to fork it and modify it.
