### ISSUE TITLE
Sample deployment.yaml for SCRAM-SHA authentication type

### ISSUE THREAD

**Issue by bharat15-ml** [strimzi/client-examples#127]
Hi, 

Could we have reference of deployment.yaml to test kafka connectivity for SCARM-SHA authentication type?

I tried taking reference of these deployments - [deployment-ssl-auth.yaml ](https://github.com/strimzi/client-examples/blob/main/java/kafka/deployment-ssl-auth.yaml) and [deployment-oauth.yaml](https://github.com/strimzi/client-examples/blob/main/java/kafka/deployment-oauth.yaml) but not sure how to pass user name and password.

Thanks!!

**Comment by scholzj** [comment]
This should be done in #136
