### ISSUE TITLE
[HTTP clients] - wrong defined YAML for http producer

### ISSUE THREAD

**Issue by see-quick** [strimzi/client-examples#143]
Our basic HTTP clients (i.e., not vertex one)  are currently not using the correct ENV to send messages. For instance, [1] producer example defines
```yaml
- name: STRIMZI_SEND_INTERVAL
   value: "1000"
```
but from the code it uses [2] `STRIMZI_DELAY_MS` env. So we should correct this and check other clients that could be defined wrongly as this one example. 

[1] - https://github.com/strimzi/client-examples/blob/main/java/http/java-http-producer.yaml
[2] - https://github.com/strimzi/client-examples/blob/main/java/http/java-http-producer/src/main/java/HttpProducerConfig.java#L40

**Comment by OwenCorrigan76** [comment]
@see-quick Looking into this. Thanks

**Comment by see-quick** [comment]
I think we could close this @OwenCorrigan76 or?

**Comment by OwenCorrigan76** [comment]
@see-quick Yes. Closing now. Thanks
