### ISSUE TITLE
Define a pattern naming for client examples Docker images

### ISSUE THREAD

**Issue by ppatierno** [strimzi/client-examples#46]
Related to #45, I had a chat with @scholzj and even because we are moving to `quay.io` it could be the right time to find a good pattern for image names for different examples (so even moving away from using "hello world" :-))
We were thinking about something like:

`<language>-<technology|framework|library>-<producer|consumer|streams>`

For example:

* java-kafka-producer ... using the native Java Kafka client
* go-sarama-consumer ... in Go using Sarama as library
* java-vertx-producer ... using the Java Vert.x client
* java-http-vertx-producer .. using HTTP with Vert.x
* go-http-consumer ... in Go using HTTP

Wdyt? @scholzj @tombentley @samuel-hawker ?

**Comment by scholzj** [comment]
I can live with it.

**Comment by Frawless** [comment]
I am ok with it as well. We just need to change it in operator system tests as well, but do it day or two after name change shouldn't break anything.

**Comment by tombentley** [comment]
SGTM
