### ISSUE TITLE
Inconsistency in created and used topics

### ISSUE THREAD

**Issue by ppatierno** [strimzi/client-examples#6]
In the `hello-world-consumer.yaml` and `hello-world-producer.yaml` files, the used topic is `my-topic` as set in the `TOPIC` env var.
In the `deployment.yaml` and `deployment-ssl.yaml` the same `TOPIC` env var is set at `hello-world-test-apps` but the YAML file contains a `KafkaTopic` resource with name `my-topic`.
It means that `my-topic` will be created by the Topic Operator while the `hello-world-test-apps` will be created on the fly just because the Kafka cluster has the `auto.create.topics.enable` property set as `true` by default. It also means that the created `my-topic` will not be used by consumer and producer.
We should have consistency between these declarations and naming and the topic used always declared through a `KafkaTopic` resource.

**Comment by sknot-rh** [comment]
Fixed by fa2f24f2889061c28ac137a3d721957da71c5d8d and 380ea93401989bf551d9f8a2f48d393950893636
